name: Workflow step

on: [push]

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Cd a directorio
        uses: actions/checkout@v3
        
      - name: HOLA MUNDO
        run: echo "HOLA MUNDO"

  second_job:
      runs-on: ubuntu-latest
      if: true
      needs: first_job

      steps:
        - name: INSTALAR DEPENDENCIAS
          run: echo "INSTALANDO DEPENDENCIAS ..."
